name: deploy-to-ecs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: <your-aws-region>

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      id: build-image
      env:
        ECR_REGISTRY: python-hello2
        IMAGE_NAME: pip
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
        docker tag $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG $ECR_REGISTRY/$IMAGE_NAME:latest

    - name: Push Docker image to Amazon ECR
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
          $ECR_REGISTRY/$IMAGE_NAME:latest
      env:
        DOCKER_BUILDKIT: 1
        ECR_REGISTRY: python-hello2
        IMAGE_NAME: pip
        IMAGE_TAG: ${{ github.sha }}

    - name: Deploy to Amazon ECS
      uses: aws-actions/am
